#!/usr/bin/env python3

print("Content-Type: text/html\n")
print("""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome to My CGI Page</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 40px;
            background-color: #f0f4f8;
            color: #333;
        }
        header {
            background: #005f73;
            color: white;
            padding: 1rem;
            border-radius: 8px;
        }
        main {
            margin-top: 20px;
            background: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
        }
        footer {
            margin-top: 20px;
            text-align: center;
            color: #777;
        }
    </style>
</head>
<body style="text-align:center;">
    <header>
        <h1>Hello from CGI!</h1>
    </header>
    <main>
        <p>This page was generated by a Python CGI script.</p>
        <p>The current time is:</p>
        <pre>
""")

from datetime import datetime
print(datetime.now().strftime("%Y-%m-%d %H:%M:%S"))

print("""
        </pre>
    </main>
    <footer>
        <p>&copy; 2025 My CGI Site</p>
    </footer>
</body>
</html>
""")
